services:
    gfksx.ListSubforumsInColumns.listener:
        class: gfksx\ListSubforumsInColumns\event\listener
        arguments:
            - @user
            - @request
        tags:
            - { name: event.listener }
